from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

data = [
    ("Hello!", False),
    ("Good morning, Lumo!", False),
    ("What time is it?", False),
    ("Remind me to buy groceries at 5 PM.", False),
    ("Turn off the lights, please.", False),
    ("I can't wait for my vacation next month!", True),
    ("I'm not a fan of spicy foods.", True),
    ("My sister's birthday is on May 15th.", True),
    ("I'm nervous about the upcoming presentation.", True),
    ("Let's have a picnic this weekend.", True),
    ("I enjoy playing tennis in my free time.", True),
    ("Set a reminder for our anniversary on August 10th.", True),
    ("Can you tell me a joke?", False),
    ("I'm excited to try the new restaurant in town.", True),
    ("What's the weather like today?", False),
    ("I prefer reading mystery novels.", False),
    ("Please turn on the lights.", False),
    ("I'm looking forward to the holiday season.", True),
    ("I have a fear of public speaking.", True),
    ("My best friend's birthday is tomorrow.", True),
    ("It's my birthday tomorrow.", True),
    ("My birthday is June 21st.", True),
    ("Let's schedule a family gathering on December 25th.", True),
    ("I dislike horror movies.", True),
    ("Remind me to call Mom on Sunday.", False),
    ("I'm excited about the concert next week.", True),
    ("What's on my calendar for tomorrow?", False),
    ("I'm not a morning person.", False),
    ("I'm planning a surprise party for my spouse.", True),
    ("Can you turn off the lights in the living room?", False),
    ("I'm a vegetarian.", True),
    ("I'm feeling a bit nervous about the job interview.", True),
    ("I can't wait to see the fireworks on New Year's Eve!", True),
    ("Please set a reminder to pay the bills on the 1st of every month.", False),
    ("I'm going to a wedding this weekend.", True),
    ("I'm excited to start my new project.", True),
    ("Check if there are any new emails.", False),
    ("My cat's birthday is on September 8th.", True),
    ("I'm not a fan of cold weather.", True),
    ("I don't like hot weather.", True),
    ("I do like warm weather.", True),
    ("I don't like rain", True),
    ("I do like rain", True),
    ("I don't like the sun", True),
    ("I like the sun", True),
    ("I hate rain", True),
    ("I hate cloudy weather", True),
    ("The sun is bright today", False),
    ("sun", False),
    ("It's very heavy rain today", False),
    ("rain", False),
    ("hate", False),
    ("I'm planning a beach trip for our anniversary.", True),
    ("Please turn on the heater.", False),
    ("I'm nervous about the dentist appointment.", True),
    ("What's the latest news?", False),
    ("I love baking cupcakes.", True),
    ("I'm looking forward to my spa day next month.", True),
    ("Anniversary", False),
    ("Birthday", False),
    ("Play some relaxing music.", False),
    ("Could you please pass the salt?", False),
    ("Turn up the volume.", False),
    ("I hope the weather gets better.", False),
    ("Please close the door.", False),
    ("I wonder what's for dinner.", False),
    ("Check the traffic conditions.", False),
    ("Is there a new movie out this weekend?", False),
    ("Can you hand me the remote?", False),
    ("I'm going to water the plants later.", False),
    ("Add milk to the shopping list.", False),
    ("I need to find a new book to read.", False),
    ("What time does the store open tomorrow?", False),
    ("Tell me a fun fact.", False),
    ("Find a recipe for chocolate chip cookies.", False),
    ("I'm planning to take a walk in the park.", False),
    ("Switch the TV channel.", False),
    ("Do you know how to fix a leaky faucet?", False),
    ("I'll probably finish this book by the weekend.", False),
    ("Please remind me to call the doctor.", False),
    ("I'm nervous", False),
    ("I'm worried", False),
    ("I'm excited", False),
    ("I'm a little excited", False),
    ("I'm a little nervous", False),
    ("I'm kinda scared", False),
    ("I'm a bit excited", False),
    ("I'm a bit terrified", False),
    ("I'm thinking of redecorating my room.", True),
    ("Could you turn down the music, please?", False),
    ("I'm planning to buy a new laptop soon.", True),
    ("Remind me to call the bank tomorrow.", False),
    ("I can't wait for the weekend to relax.", False),
    ("Set a reminder for our anniversary next month.", True),
    ("Can you set a reminder to pick up flowers for my anniversary.", True),
    ("Can you set a reminder to pick of flowers.", False),
    ("I love hiking in the mountains.", True),
    ("My favorite color is blue.", True),
    ("I dislike spicy food.", True),
    ("I'm excited about my upcoming vacation.", True),
    ("I enjoy reading science fiction novels.", True),
    ("Today is my birthday!", True),
    ("I need to buy groceries.", False),
    ("Can you set a reminder for my appointment?", False),
    ("Please play my favorite song.", False),
    ("What time is it?", False),
    ("I'm feeling tired after a long day.", False),
    ("I have a meeting at 10 AM.", False),
    ("I can't wait to watch the new movie.", True),
    ("I prefer tea over coffee.", True),
    ("I'm nervous about giving a presentation.", True),
    ("I'm planning a surprise party.", True),
    ("I need to pick up dry cleaning.", False),
    ("Can you recommend a good restaurant?", False),
    ("I enjoy painting landscapes.", True),
    ("I'm looking forward to the weekend.", False),
    ("I'm allergic to seafood.", True),
    ("I'm getting a new pet next week.", True),
    ("I'm practicing for a piano recital.", True),
    ("I enjoy gardening and growing plants.", True),
    ("I'm trying to cut down on sugar.", True),
    ("I have a dentist appointment tomorrow.", False),
    ("Can you help me solve this math problem?", False),
    ("I'm thinking of redecorating my room.", True),
    ("I have to catch an early morning flight.", False),
    ("I'm attending a friend's wedding this weekend.", True),
    ("I'm planning a road trip with friends.", True),
    ("I'm researching recipes for a special dinner.", True),
    ("I need to finish a work project by Friday.", False),
    ("I'm going to a fitness class this evening.", True),
    ("I'm saving up for a new laptop.", True),
    ("I need to pick up my prescription from the pharmacy.", False),
    ("I'm learning to speak French.", True),
    ("I have a job interview next month.", True),
    ("I'm organizing a charity fundraiser.", True),
    ("I'm attending a virtual conference tomorrow.", False),
    ("I'm trying to schedule a doctor's appointment, but their online system isn't working.", False),
    ("I'm looking for recommendations for a restaurant that serves authentic Thai cuisine.", False),
    ("I'm really craving pizza right now.", False),
    ("I feel so sleepy after that long movie.", False),
    ("I can't believe how excited I am for the weekend.", False),
    ("Ugh, Mondays are the worst.", False),
    ("I'm feeling a bit under the weather today.", False),
    ("That movie made me laugh so hard!", False),
    ("I'm so frustrated with this traffic jam.", False),
    ("The sunset tonight was absolutely beautiful.", False),
    ("I'm a little anxious about the upcoming exam.", False),
    ("I love the smell of freshly baked cookies.", False),
    ("I'm in a really good mood after talking to my friend.", False),
    ("The suspense in that book is killing me.", False),
    ("I'm craving some ice cream to beat this heat.", False),
    ("The concert last night was so much fun.", False),
    ("I'm feeling a bit overwhelmed with all these tasks.", False),
    ("I can't believe how cute that puppy is!", False),
    ("I'm feeling quite content just relaxing at home.", False),
    ("The rain always puts me in a nostalgic mood.", False),
    ("I'm really excited about trying out that new restaurant.", False),
    ("I'm feeling a little jealous of my friend's vacation photos.", False),
    ("I'm fascinated by astronomy and get a sense of wonder every time I gaze at the stars.", True),
    ("I love hiking in the mountains.", True),
    ("Have you ever tried hiking? It's so refreshing!", False),
    ("My birthday is tomorrow!", True),
    ("When is your birthday?", False),
    ("I'm excited about my upcoming vacation.", True),
    ("Have you ever been on a vacation? It's a great way to unwind.", False),
    ("My favorite color is blue.", True),
    ("Do you like the color blue, or do you have a different favorite?", False),
    ("I'm practicing for a piano recital.", True),
    ("Have you ever tried playing the piano? It's quite enjoyable.", False),
    ("I'm allergic to seafood.", True),
    ("Do you have any allergies?", True),
    ("I'm looking forward to my birthday party.", True),
    ("Do you usually celebrate your birthday with a party?", False),
    ("I'm excited about the new movie release.", True),
    ("Are you a fan of going to the movies? I love watching films.", False),
    ("I enjoy painting landscapes.", True),
    ("Have you ever tried painting? It's a great way to express yourself.", False),
    ("I'm nervous about giving a presentation.", True),
    ("Have you ever had to give a public speech? It can be quite daunting.", False),
    ("I'm practicing my baking skills.", True),
    ("Do you like baking? I find it to be a relaxing hobby.", False)
]

# Separate text and labels
texts = [doc[0] for doc in data]
labels = [doc[1] for doc in data]

# Create a CountVectorizer to convert text data into numerical features
vectorizer = CountVectorizer()
train_vec = vectorizer.fit_transform(texts)

# Create and train a Multinomial Naive Bayes classifier
classifier = MultinomialNB()
classifier.fit(train_vec, labels)

def is_important(text: str):
    new_text_vec = vectorizer.transform([text])
    
    return classifier.predict(new_text_vec)[0]